default_context:
  author: Your Name
  email: yname@gmail.com
  project_name_full: Module Name
  project_name: "{{ cookiecutter.project_name_full.lower().replace(' ', '_') }}"
  project_short_description: Cpp Module. Compile with CMake
  version: '0.5'
  cmake_version: '3.0'
